// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7cxYqFxMlb9Bk9oV09WB-0-5WcAP3F4',
    appId: '1:757028999155:web:448915e9d24a341b9fcc86',
    messagingSenderId: '757028999155',
    projectId: 'arise-register',
    authDomain: 'arise-register.firebaseapp.com',
    storageBucket: 'arise-register.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrUpo-YZvG8F826KGM3cOzDgEM5JwMlU',
    appId: '1:757028999155:android:acbc496b00ce97319fcc86',
    messagingSenderId: '757028999155',
    projectId: 'arise-register',
    storageBucket: 'arise-register.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ibFaFuodjnfwAA52EW9wjl2sbD4aNis',
    appId: '1:757028999155:ios:87b89c53814914b39fcc86',
    messagingSenderId: '757028999155',
    projectId: 'arise-register',
    storageBucket: 'arise-register.firebasestorage.app',
    iosBundleId: 'com.example.ariseRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ibFaFuodjnfwAA52EW9wjl2sbD4aNis',
    appId: '1:757028999155:ios:87b89c53814914b39fcc86',
    messagingSenderId: '757028999155',
    projectId: 'arise-register',
    storageBucket: 'arise-register.firebasestorage.app',
    iosBundleId: 'com.example.ariseRegister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR7cxYqFxMlb9Bk9oV09WB-0-5WcAP3F4',
    appId: '1:757028999155:web:c074d86470c3c4e89fcc86',
    messagingSenderId: '757028999155',
    projectId: 'arise-register',
    authDomain: 'arise-register.firebaseapp.com',
    storageBucket: 'arise-register.firebasestorage.app',
  );
}
